FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD intelcore.jar /opt/intelcore/
EXPOSE 8080
WORKDIR /opt/intelcore/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "intelcore.jar"]
